lmapp.controller('lmjCtrl',function($scope,scroll){
    scroll.iscroll();
    $scope.lmjCont={
        lmjcard:[
                {
                    imgsrc:"image/cardimg/summer.jpg",
                    tags:"夏天"
                },
                {
                    imgsrc:"image/cardimg/dog.jpg",
                    tags:"宠物"
                },
                {
                    imgsrc:"image/cardimg/summer.jpg",
                    tags:"夏天"
                },
                {
                    imgsrc:"image/cardimg/dog.jpg",
                    tags:"宠物"
                },
                {
                    imgsrc:"image/cardimg/summer.jpg",
                    tags:"夏天"
                },
                {
                    imgsrc:"image/cardimg/dog.jpg",
                    tags:"宠物"
                },
                {
                    imgsrc:"image/cardimg/summer.jpg",
                    tags:"夏天"
                },
                {
                    imgsrc:"image/cardimg/dog.jpg",
                    tags:"宠物"
                }
            ]
        }
    });